
- name: deploy powergate
  docker_container:
    name: "powergate"
    image: "textile/powergate"
    env:
      POWD_LOTUSHOST: "/dns4/lotus/tcp/1234"
      POWD_IPFSAPIADDR: "/dns4/ipfs/tcp/5001"
      POWD_LOTUSTOKENFILE: "/root/lotus/.lotus/token"
      POWD_REPOPATH: "/root/powergate/.powergate"
    network_mode: "syntropy_network"
    volumes:
      - powergate-powd:/root/powergate
      - powergate-lotus:/root/lotus
    ports:
      - 8889:8889
      - 8888:8888
      - 6060:6060
      - 5002:5002
      - 6002:6002
      - 7000:7000
    networks: 
      - name: "syntropy_network"
        ipv4_address: "10.52.2.7"
    detach: yes